### ISSUE TITLE
Cannot read properties of null (reading 'tickConsumer')

### ISSUE THREAD

**Issue by fasblom** [alexandrainst/node-red-contrib-postgresql#33]
Hi,

I am using the node-red-contrib-postgresql to insert data into a postgres db. I have this error with one my my flows: 

`4 Jan 09:02:43 - [error] TypeError: Cannot read properties of null (reading 'tickConsumer')
    at /data/node_modules/node-red-contrib-postgresql/postgresql.js:159:74
    at findInputNodeId (/data/node_modules/node-red-contrib-postgresql/postgresql.js:19:49)
    at PostgreSQLNode._inputCallback (/data/node_modules/node-red-contrib-postgresql/postgresql.js:159:22)
    at /usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/src/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at PostgreSQLNode.Node._emitInput (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at PostgreSQLNode.Node.emit (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at PostgreSQLNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
    at Immediate.<anonymous> (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (node:internal/timers:466:21)
`

Any ideas?

**Comment by Alkarex** [comment]
Hello,
Which version of Node-RED do you run? And could you maybe share a minimal flow triggering the bug?
